### ISSUE TITLE
Sharing 3 Windows for Video Causes Application Error

### ISSUE THREAD

**Issue by chrisyoungr** [AugmendTech/issues-and-feedback#16]
Upon selecting 3 windows to share (Postman, Visual Code Studio and Google Chrome), the following error appears.  
![image](https://github.com/AugmendTech/issues-and-feedback/assets/35730876/d1552938-12ea-48ac-b5cd-553db0cf91b2)

If I click okay and record, the recording appears to continue, but ultimately does not record.  I have replicated twice.  

Happy to share more details to help the team replicate this.

**Comment by dbish** [comment]
Thanks Chris, we're taking a look. Tim will let you know if he needs any more info to find what's happening

**Comment by TimMisiak** [comment]
Would you be able to share your latest logs from one of the sessions that failed? Logs go in the temp directory and are named "%temp%\augmend_client_*"

**Comment by chrisyoungr** [comment]
@TimMisiak sure.  Here you go.  One hypothesis I have is that I was running a local server because what I wanted to record was in my local environment.  I'm wondering if me running that somehow conflicts with your program.  
[augmend_client_5_9_2024__13_28.log](https://github.com/AugmendTech/issues-and-feedback/files/15265968/augmend_client_5_9_2024__13_28.log)
[augmend_client_5_9_2024__13_45.log](https://github.com/AugmendTech/issues-and-feedback/files/15265969/augmend_client_5_9_2024__13_45.log)

**Comment by chrisyoungr** [comment]
You can disregard my hypothesis @TimMisiak .  I tried deactivating my local server and it still encountered the issue.

**Comment by TimMisiak** [comment]
Thanks! Looks like it hit an error on the server side. I made a quick fix on the server that I think will help. Can you try again and see if you hit the same issue?

**Comment by chrisyoungr** [comment]
@TimMisiak it worked now. Thanks

**Comment by TimMisiak** [comment]
Great, glad it's working now!
